dataset_path: ./data/train_data_sas.csv
reward_index: 139
observation:
  space: 155
  discrete_space: 132
  discrete_space_sections: !!python/tuple [5, 2, 4, 3, 2, 9, 2, 32, 35, 7, 2, 21, 2, 3, 3]
  continuous_space: 23
action:
  space: 6
  discrete_space: 0
  continuous_space: 6